### PR TITLE
Hardware Readme

### PR DESCRIPTION
**Pull request by faddat**
Created projects folder, created hardware folder, created a readme that lay's out why and lays out what.

### CODE REVIEW

**Comment by nylira** [comment]
@faddat thanks for the contribution! Can you make this under `./Teams/Hardware` instead of adding a new top-level folder?

**Comment by faddat** [comment]
Happy to :).

**Comment by faddat** [comment]
All set

**Comment by nylira** [comment]
Thanks for your patience @faddat!

**Pull request merged**
