### PR TITLE
Adding list of projects relevant to the UDV

### PR DESCRIPTION
**Pull request by haymond**

### CODE REVIEW

**Comment by nylira** [comment]
I like the list but I'm concerned that the README is already too long, and it will be hard to find these. Do you want to put them in the website instead?

**Comment by haymond** [comment]
Good point. How about I close this and add it to UNSORTED.MD until we have more clarity on these topics?

**Comment by nylira** [comment]
Sounds good!

**Comment by haymond** [comment]
Closing this and moving to UNSORTED.md.

**Pull request closed without merging**
